# Generated by Django 4.0 on 2022-01-13 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_profile_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='darkmode',
            field=models.BooleanField(default=False),
        ),
    ]
